# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# declaring variables
pm=pacman # package manager variable
aurh=yay # aur helper variable
editor=nvim # text editor variable
country=MC # choose the country that is closest to you

# activate vi mode in bash
set -o vi

# run neofetch
#neofetch

# terminal files stuff
alias ls='ls --color=auto' # list unhidden files and directories with colors
alias la='ls -a' # list both hidden and unidden files and directories
alias l='ls -lh' # ls with the -l (columns) and -h (human readable format) flags
alias ll='l -a' # la + l = ll
alias lsu='ls /media/usb' # list what is in your usb device ( '/media/usb' directory)
alias grep='grep --color=auto' # grep with colors
alias rmr='sudo rm -rf' # remove (delete) files and directories completly from your system (can't recover them)
alias scp='sudo cp' # added sudo privllages to cpoying files
alias cpr='cp -r' # copy entire directories
alias scpr='sudo cp -r' # The previous alias with sudo privileges
alias smkdir='sudo mkdir' # gives sudo privileges to the mkdir command

# pacman & yay
alias pi='sudo '$pm' -S' # Pacman Install
alias py='sudo '$pm' -Syy' # Pacman Install
alias pr='sudo '$pm' -Rs' # Pacman Remove
alias ps=''$pm' -Ss' # Pacman Search
alias pq=''$pm' -Q' # Pacman Query
alias pqi=''$pm' -Qi' # Pacman Query Installed
alias pqo=''$pm' -Qdt' # Pacman Query a certain program
alias pu='sudo '$pm' -Syu' # Pacman Update
alias pc='sudo '$pm' -Sc' # Pacman Clear cache
alias yi=''$aurh' -S' # Yay Install
alias ys=''$aurh' -Ss' # Yay Search
alias ref='sudo reflector -c '$country' --latest 10 --sort rate --save /etc/pacman.d/mirrorlist' # Setting the fastest mirrors that are the closest to the selected country

# power management
alias po='sudo poweroff' # PowerOff (Shutdown) your system
alias rb='sudo reboot' # ReBoot your system

# suckless stuff
alias m='make' # Simple alias for the make command
alias mc='make clean && sudo rm config.h' # The previous alias with the clean and remove config.h options added to it for suckless software
alias mic='sudo make install clean && rm config.h' # The previous alias with the install option and sudo privileges added to it

# usb actions
alias musb='sudo mount /dev/sdc1 /media/usb' # Mount USB drive
alias uusb='sudo umount /dev/sdc1' # Unmount USB drive
alias eusb='sudo eject /dev/sdc' # Eject USB drive
alias mwin='sudo mount /dev/sda1 /mnt/win/' # mount your windows C: drive

# neovim shortcuts
alias vi=''$editor'' # Replace nvim with vi (visual editor) using when the terminal
alias svi='sudo '$editor'' # The previous alias with sudo privileges
alias vib=''$editor' ~/.bashrc' # Edit the bashrc file
alias vix=''$editor' ~/.xinitrc' # Edit the xinitrc file
alias vin=''$editor' ~/.config/nvim/init.lua' # Edit the Neovim init.lua config file
alias mir='sudo '$editor' /etc/pacman.d/mirrorlist' # Edit the pacman mirrorlist file

# other stuff
alias xwz='xwallpaper --zoom' # set your wallpaper
alias sbrc='source ~/.bashrc' # source your bashrc file
alias sx='startx' # simple alias for the startx command
alias yt='yt-dlp' # simple alias for the yt-dlp command
alias df='df -h' # adding the -h (human readable format) flag to the df command
alias kfdm='pkill -e fdm' # alias for killing fdm (free download manager)
alias ssystemctl='sudo systemctl' # adding sudo privileges to the systemctl command
alias cpio='sudo mkinitcpio -P' # simple alias for the mkinitcpio command
alias top='htop' # replace top with htop
alias neofetch='clear && neofetch'
alias cl='clear'

# bash prompt customization
#PS1='[\u@\h \W]\$ ' # default
PS1="\[\e[1;32m\] \w \[\e[1;34m\] \[\e[1;37m\] " # personal
